Repository This-is-XiaoDeng/XDbot2, pull requests merged in 2023-04, with the labels that each got.

#119 [update] 消灭浮点误差，世界属于Decimal！
  src/plugins/Core/plugins/sign.py
  src/plugins/Core/plugins/version.py
Labels: 等待反馈者, · 优化

#121 修改语言文件
  src/plugins/Core/lang/en_laman28.json
  src/plugins/Core/plugins/su_ban.py
  src/plugins/Core/plugins/su_config.py
Labels: · 优化

#125 优化物品功能
  .env.prod
  .gitignore
  README.md
  src/plugins/Core/lang/zh_hans.json
  src/plugins/Core/plugins/_error.py
  src/plugins/Core/plugins/bag.py
  src/plugins/Core/plugins/etm/bag.py
  src/plugins/Core/plugins/quick_math.py
  src/plugins/Core/plugins/su_old.py
  src/plugins/Core/plugins/use.py
  src/plugins/Core/plugins/userinfo.py
Labels: · 优化

#129 [add] sentry
  requirements.txt
  src/plugins/nonebot_plugin_sentry/README.md
  src/plugins/nonebot_plugin_sentry/__init__.py
  src/plugins/nonebot_plugin_sentry/config.py
  src/plugins/nonebot_plugin_sentry/pyproject.toml
Labels: · 新功能
