Repository This-is-XiaoDeng/XDbot2, pull requests merged in 2023-01, with the labels that each got.

#22 [add] 添加 su cave modify 命令及其帮助手册 man su (25~28)
  docs/su/0.md
  docs/su/25.md
  docs/su/26.md
  docs/su/27.md
  docs/su/28.md
  src/plugins/Core/plugins/su.py
Labels: enhancement

#23 [fix] su cave modify 数据访问错误
  src/plugins/Core/plugins/su.py
Labels: · Bug

#24 [add] sign (rank) 时显示下次可签到时间
  src/plugins/Core/plugins/sign.py
Labels: · 优化

#25 [update] 修改部分提示文本
  src/plugins/Core/plugins/autosell.py
  src/plugins/Core/plugins/bag.py
  src/plugins/Core/plugins/ban.py
  src/plugins/Core/plugins/cave.py
  src/plugins/Core/plugins/guess.py
  src/plugins/Core/plugins/jrrp.py
  src/plugins/Core/plugins/linuxman.py
  src/plugins/Core/plugins/man.py
  src/plugins/Core/plugins/messenger.py
  src/plugins/Core/plugins/reply.py
  src/plugins/Core/plugins/report.py
  src/plugins/Core/plugins/rule.py
  src/plugins/Core/plugins/setu.py
  src/plugins/Core/plugins/shop.py
  src/plugins/Core/plugins/sign.py
  src/plugins/Core/plugins/st.py
  src/plugins/Core/plugins/use.py
  src/plugins/Core/plugins/userInfo.py
  src/plugins/Core/plugins/whoAtme.py
Labels: · 优化

#26 [add] 本 地 化
  .idea/.gitignore
  .idea/XDbot2.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/plugins/Core/lang/zh_fzz.json
  src/plugins/Core/plugins/_error.py
  src/plugins/Core/plugins/_lang.py
  src/plugins/Core/plugins/_userCtrl.py
  src/plugins/Core/plugins/autosell.py
  src/plugins/Core/plugins/bag.py
  src/plugins/Core/plugins/cave.py
  src/plugins/Core/plugins/ct.py
  src/plugins/Core/plugins/fakenode.py
  src/plugins/Core/plugins/forward.py
  src/plugins/Core/plugins/guess.py
  src/plugins/Core/plugins/help.py
  src/plugins/Core/plugins/jrrp.py
  src/plugins/Core/plugins/lang.py
  src/plugins/Core/plugins/linuxkernelnews.py
  src/plugins/Core/plugins/linuxman.py
  src/plugins/Core/plugins/man.py
  src/plugins/Core/plugins/messenger.py
  src/plugins/Core/plugins/reply.py
  src/plugins/Core/plugins/report.py
  src/plugins/Core/plugins/rule.py
  src/plugins/Core/plugins/setu.py
  src/plugins/Core/plugins/shop.py
  src/plugins/Core/plugins/sign.py
  src/plugins/Core/plugins/status.py
  src/plugins/Core/plugins/use.py
  src/plugins/Core/plugins/userInfo.py
  src/plugins/Core/plugins/vote.py
  src/plugins/Core/plugins/whoAtme.py
Labels: · 新功能

#27 [update] 整理代码 & 修复二十面骰文本不能正确本地化
  src/plugins/Core/plugins/_error.py
  src/plugins/Core/plugins/_lang.py
  src/plugins/Core/plugins/_userCtrl.py
  src/plugins/Core/plugins/autosell.py
  src/plugins/Core/plugins/bag.py
  src/plugins/Core/plugins/ban.py
  src/plugins/Core/plugins/cave.py
  src/plugins/Core/plugins/ct.py
  src/plugins/Core/plugins/fakenode.py
  src/plugins/Core/plugins/forward.py
  src/plugins/Core/plugins/guess.py
  src/plugins/Core/plugins/help.py
  src/plugins/Core/plugins/jrrp.py
  src/plugins/Core/plugins/lang.py
  src/plugins/Core/plugins/linuxkernelnews.py
  src/plugins/Core/plugins/linuxman.py
  src/plugins/Core/plugins/man.py
  src/plugins/Core/plugins/messenger.py
  src/plugins/Core/plugins/reply.py
  src/plugins/Core/plugins/report.py
  src/plugins/Core/plugins/rule.py
  src/plugins/Core/plugins/setu.py
  src/plugins/Core/plugins/shop.py
  src/plugins/Core/plugins/sign.py
  src/plugins/Core/plugins/sixcount.py
  src/plugins/Core/plugins/st.py
  src/plugins/Core/plugins/status.py
  src/plugins/Core/plugins/su.py
  src/plugins/Core/plugins/use.py
  src/plugins/Core/plugins/userInfo.py
  src/plugins/Core/plugins/vote.py
  src/plugins/Core/plugins/whoAtme.py
Labels: · Bug, · 优化

#31 [add] 增加了zh_yf
  src/plugins/Core/lang/zh_yf.json
Labels: · 优化
